services:
  - type: web
    name: LaravelApp
    env: php
    region: us-central
    plan: free
    buildCommand: 'composer install && npm install && npm run prod && php artisan migrate --force'
    startCommand: 'php artisan serve --host 0.0.0.0 --port 10000'
    envVars:
      - key: APP_KEY
        sync: false
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: 127.0.0.1
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: practica0
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: F_fuentes824
